### ISSUE TITLE
association of tag to tickets from project doesn't work

### ISSUE THREAD

**Issue by Frux007** [pluginsGLPI/tag#85]
When you want to add a tag on all ticket added as ITIL object of a project, the tag list is empty and not usable

![image](https://user-images.githubusercontent.com/59683014/72049354-132bc780-32bf-11ea-95ec-f562aba0a87e.png)

this works fine when you are on the tickets listing
![image](https://user-images.githubusercontent.com/59683014/72048597-71f04180-32bd-11ea-9ba0-af56152ce482.png)

regards.

GLPI version : 9.4.5
tag plugin version : 2.5.0

**Comment by stonebuzz** [comment]
Hi @Frux007, this comportement will be fixed on next release.


Normally, the plugin should not display the option to add a tag for a subitem (ie : Ticket / Change on Project or Computer on Project).

In addition, in this list, there can be different types of items such as Ticket / Change / Problem,
A massive action process here would be complicated because the tags are linked to different types of items 

at the tag selection step, the plugin won't know which tag to propose to you because there may be several item types selected.

We've made  PR to fix this behavior.

If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

I’m closing this issue, feel free to continue discussion here if you want.
